### 3.5.2. Llama3 학습 파라미터 설정
model_name: "allganize/Llama-3-Alpha-Ko-8B-Instruct"
dataset_path: "."
max_seq_length: 512
output_dir: "./llama-3.1-korean-8b-hf-20-epoch"
report_to: "wandb"
learning_rate: 0.00005
lr_scheduler_type: "linear"
num_train_epochs: 5
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 4
optim: "adamw_torch_fused"
logging_steps: 10
save_strategy: "epoch"
weight_decay: 0.01
max_grad_norm: 0.5
warmup_ratio: 0.03
bf16: true
tf32: true
gradient_checkpointing: true
<<<<<<< HEAD:Fine-tuning/2.Finetuning/full_fine_tuning_config.yaml
<<<<<<< HEAD
#fsdp: "full_shard auto_wrap"
#fsdp_config:
#  backward_prefetch: "backward_pre"
#  forward_prefetch: "false"
#  use_orig_params: "false"